### ISSUE TITLE
Create a new version, update podspec and pod trunk push

### ISSUE THREAD

**Issue by dasmer** [thisandagain/color#34]
We're trying to use the ```darken:``` method, but an updated version for this library has not been created since they method was written. 

Awesome library btw :octocat:

**Comment by thisandagain** [comment]
Good point! :+1: will do.

**Comment by thisandagain** [comment]
All set:
https://github.com/CocoaPods/Specs/tree/master/Specs/EDColor/1.0.0

**Comment by dblock** [comment]
Thanks for cutting a release @thisandagain !

**Comment by dasmer** [comment]
Thanks @thisandagain !
