### ISSUE TITLE
UIColor+HSB.h:15:5: No newline at end of file

### ISSUE THREAD

**Issue by mteece** [thisandagain/color#40]
Receiving a UIColor+HSB.h:15:5: No newline at end of file. The compiler flags for no newline at end of file [-Werror,-Wnewline-eof].

Using Cocoapods with Using EDColor (1.0.0).

**Comment by dblock** [comment]
Please PR!

**Comment by mteece** [comment]
Looks as though #39 was looking into this. Did this get merged in and the pod spec updated?

**Comment by mteece** [comment]
It appears the #39 was merged into master, but no new pod spec version was added to support it or the Podspec file ' s.source' needs a new tag created to capture that for everyone using cocoapods.

Master is ahead of 1.0.0 tag, so a 1.0.1 tag needs to be created and the new Podspec pushed to Cocoapods so everyone else who uses Cocoapods can capture that version. Only owners can do this as far as I understand pushing to the master pod repo.

A quickfix is to hard code to master in the Podfile of your project.

pod 'EDColor', :git => 'https://github.com/thisandagain/color.git'

**Comment by dblock** [comment]
Closed via https://github.com/thisandagain/color/issues/39. 

I'll open an issue for a release, maybe I'll get to it soon.
